### ISSUE TITLE
Error while downloading tsugumomo

### ISSUE THREAD

**Issue by TheDogHusky** [tohyongcheng/mangapark-dl#8]
Hey!

I've been interested in this project as I wanted to be able to download my mangas in PDF from mangapark.
I tried running the following command: `./.venv/bin/python3 main.py -m https://mangapark.me/title/27918-en-tsugumomo --chapters 0 171` (also tried from chapter 1)
Sadly, I got greeted with an error:
```
adam@adam-VMware-Virtual-Platform:~/Documents/mangapark-dl$ ./.venv/bin/python3 main.py -m https://mangapark.me/title/27918-en-tsugumomo --chapters 1 171
Namespace(manga_url='https://mangapark.me/title/27918-en-tsugumomo', size=None, chapter=None, chapters=['1', '171'])
Traceback (most recent call last):
  File "/home/adam/Documents/mangapark-dl/main.py", line 245, in <module>
    main()
  File "/home/adam/Documents/mangapark-dl/main.py", line 238, in main
    download_manga(args.manga_url, min_max=[float(x) for x in args.chapters], height=args.size)
  File "/home/adam/Documents/mangapark-dl/main.py", line 202, in download_manga
    max_stream_len = max(stream_lens)
                     ^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```
(if I'm in a vm, it's because I couldn't get python to work correctly on my windows PC)

All packages are installed correctly.

I would love some help, and I can sadly not contribute to the project, as I'm really far from being a python developer.

cheers,
Adam

**Comment by etashj** [comment]
I know I'm a few months late, but I had this exact same issue and just wrote a selenium web scraper for mangapark downloading. 

https://github.com/etashj/mangapark-dl/
